//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Photo = new HashSet<Photo>();
            this.Story = new HashSet<Story>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
    
        public virtual GeneralPost GeneralPost { get; set; }
        public virtual ICollection<Photo> Photo { get; set; }
        public virtual ICollection<Story> Story { get; set; }
    }
}
