//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public Family()
        {
            this.FamilyRole = new HashSet<FamilyRole>();
            this.Neighborhood = new HashSet<Neighborhood>();
            this.Neighborhood1 = new HashSet<Neighborhood>();
            this.NeighborRequest = new HashSet<NeighborRequest>();
            this.Sharing = new HashSet<Sharing>();
            this.User = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string coverURL { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<FamilyRole> FamilyRole { get; set; }
        public virtual ICollection<Neighborhood> Neighborhood { get; set; }
        public virtual ICollection<Neighborhood> Neighborhood1 { get; set; }
        public virtual ICollection<NeighborRequest> NeighborRequest { get; set; }
        public virtual ICollection<Sharing> Sharing { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
