//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamsamEntities : DbContext
    {
        public FamsamEntities()
            : base("name=FamsamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Family> Family { get; set; }
        public virtual DbSet<FamilyRole> FamilyRole { get; set; }
        public virtual DbSet<GeneralPost> GeneralPost { get; set; }
        public virtual DbSet<Neighborhood> Neighborhood { get; set; }
        public virtual DbSet<NeighborRequest> NeighborRequest { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Sharing> Sharing { get; set; }
        public virtual DbSet<Story> Story { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
