//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralPost
    {
        public GeneralPost()
        {
            this.Comment = new HashSet<Comment>();
            this.User1 = new HashSet<User>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string postType { get; set; }
        public Nullable<int> author { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual User User { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual Story Story { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
