//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighborhood
    {
        public int familyId { get; set; }
        public int neighborId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Family Family1 { get; set; }
    }
}
