//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeighborRequest
    {
        public int userId { get; set; }
        public int familyId { get; set; }
        public string status { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual User User { get; set; }
    }
}
