//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sharing
    {
        public int userId { get; set; }
        public int storyId { get; set; }
        public int sharedFamilyId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string message { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Story Story { get; set; }
        public virtual User User { get; set; }
    }
}
