//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comment = new HashSet<Comment>();
            this.FamilyRole = new HashSet<FamilyRole>();
            this.GeneralPost = new HashSet<GeneralPost>();
            this.NeighborRequest = new HashSet<NeighborRequest>();
            this.Report = new HashSet<Report>();
            this.Session = new HashSet<Session>();
            this.Sharing = new HashSet<Sharing>();
            this.Family = new HashSet<Family>();
            this.GeneralPost1 = new HashSet<GeneralPost>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string about { get; set; }
        public string workAt { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string phone { get; set; }
        public Nullable<bool> infoPrivacy { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string avatarURL { get; set; }
        public string status { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<FamilyRole> FamilyRole { get; set; }
        public virtual ICollection<GeneralPost> GeneralPost { get; set; }
        public virtual ICollection<NeighborRequest> NeighborRequest { get; set; }
        public virtual ICollection<Report> Report { get; set; }
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<Sharing> Sharing { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<Family> Family { get; set; }
        public virtual ICollection<GeneralPost> GeneralPost1 { get; set; }
    }
}
