-- MySQL Script generated by MySQL Workbench
-- 09/20/14 00:51:16
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `famsam` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `famsam` ;

CREATE TABLE IF NOT EXISTS `famsam`.`UserRole` (
  `roleName` varchar(10) NOT NULL,
  `description` varchar(20) NULL,
  PRIMARY KEY (`roleName`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `famsam`.`User` (
  `id` int NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `roleName` varchar(10) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(20) NOT NULL,
  `birthday` datetime NULL,
  `phone` varchar(10) null,
  `address` varchar(255) null,
  `country` varchar(20) null,
  `avatarURL` varchar(255) null,
  `status` varchar(10) null,
  PRIMARY KEY (`id`),
  CONSTRAINT fk_User_UserRole FOREIGN KEY (`roleName`) REFERENCES `famsam`.`UserRole`(`roleName`)
)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `famsam`.`Family` (
  `id` int NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `date` datetime NOT NULL,
  `coverURL` VARCHAR(255) NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
  )
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `famsam`.`FamilyRole` (
  `family_id` int NOT NULL,
  `user_id` int not null,
  `roleName` varchar(20) not null,
  `dateJoin` datetime not null,
  PRIMARY KEY (`family_id`, `user_id`),
  CONSTRAINT fk_FamilyRole_Family FOREIGN KEY (`family_id`) REFERENCES `famsam`.`Family`(`id`),
  CONSTRAINT fk_FamilyRole_User FOREIGN KEY (`user_id`) REFERENCES `famsam`.`User`(`id`)
)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `famsam`.`Neighborhood` (
  `familyid` int NOT NULL,
  `neighborid` int NOT NULL,
  PRIMARY KEY (`familyid1`,`familyid2`),
  CONSTRAINT fk_Neighborhood_Family FOREIGN KEY (`familyid`) REFERENCES `famsam`.`Family`(`id`),
  CONSTRAINT fk_Neighborhood_Neighbor FOREIGN KEY (`neighborid`) REFERENCES `famsam`.`Family`(`id`)

)
ENGINE = InnoDB;

Create Table If Not Exists `famsam`.`NeighborRequest` (
  `user_id` int not null,
  `family_id` int not null,
  Primary Key (`user_id`, `family_id`),
  Constraint fk_NeighborRequest_User Foreign Key (`user_id`) references `famsam`.`User`(`id`),
  Constraint fk_NeighborRequest_Family Foreign Key (`family_id`) references `famsam`.`Family`(`id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famsam`.`Story` (
  `id` int NOT NULL,
  `title` VARCHAR(50) NULL,
  `isShared` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `id` MEDIUMTEXT NOT NULL,
  `title` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo` (
  `id` MEDIUMTEXT NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `badQuality` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GeneralPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GeneralPost` (
  `id` MEDIUMTEXT NOT NULL,
  `description` VARCHAR(500) NULL,
  `lastUpdated` DATETIME NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `id` MEDIUMTEXT NOT NULL,
  `contain` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL,
  `userid` MEDIUMTEXT NOT NULL,
  `postid` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Like` (
  `id` MEDIUMTEXT NOT NULL,
  `userid` MEDIUMTEXT NOT NULL,
  `postid` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Follow_Family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Follow_Family` (
  `id` MEDIUMTEXT NOT NULL,
  `userid` MEDIUMTEXT NOT NULL,
  `familyid` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report_Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report_Photo` (
  `id` MEDIUMTEXT NOT NULL,
  `userid` MEDIUMTEXT NOT NULL,
  `photoid` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
