-- MySQL Script generated by MySQL Workbench
-- 09/19/14 12:19:19
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `id` int NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(30) NULL,
  `firstname` VARCHAR(20) NULL,
  `lastname` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` int NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(20) NOT NULL,
  `birthdate` DATETIME NULL,
  `phone` VARCHAR(50) NULL,
  `address` VARCHAR(200) NULL,
  `country` VARCHAR(30) NULL,
  `avatarURL` VARCHAR(200) NULL,
  `status` INT NOT NULL,
  `reason` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Family` (
  `id` int NOT NULL,
  `familyname` VARCHAR(100) NOT NULL,
  `dateCreated` DATETIME NOT NULL,
  `coverURL` VARCHAR(200) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Family_Rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Family_Rel` (
  `id` int NOT NULL,
  `familyid` MEDIUMTEXT NULL,
  `userid` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Family_Rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Family_Rel` (
  `id` int NOT NULL,
  `familyid1` MEDIUMTEXT NOT NULL,
  `familyid2` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `id` int NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  `expired` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Story` (
  `id` int NOT NULL,
  `title` VARCHAR(50) NULL,
  `isShared` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `id` int NOT NULL,
  `title` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo` (
  `id` int NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `badQuality` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GeneralPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GeneralPost` (
  `id` int NOT NULL,
  `description` VARCHAR(500) NULL,
  `lastUpdated` DATETIME NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `id` int NOT NULL,
  `contain` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL,
  `userid` MEDIUMTEXT NOT NULL,
  `postid` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Like` (
  `id` int NOT NULL,
  `userid` MEDIUMTEXT NOT NULL,
  `postid` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Follow_Family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Follow_Family` (
  `id` int NOT NULL,
  `userid` MEDIUMTEXT NOT NULL,
  `familyid` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report_Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report_Photo` (
  `id` int NOT NULL,
  `userid` int NOT NULL,
  `photoid` int NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
